#!/bin/bash

rm -fr Documents Music Pictures Public Templates Videos

sudo apt-get update
sudo apt-get remove chromium-browser lubuntu-software-center
sudo apt-get install gcc g++ make emacs firefox vlc zsnes avidemux scummvm dosbox git dkms inkscape
#cp -r /media/matthew/VBoxLinuxAdditions.run
#sudo ./VBoxLinuxAdditions.run


#Set up OpengL
sudo apt-get install freeglut3 freeglut3-dev libglew-dev libglew1.5 binutils-gold


sudo apt-get upgrade

git clone https://github.com/mallouk/linuxSettings.git
cd linuxSettings/
cp -r * ~/
cp -r .* ~/
cd

